on:
  push:
    branches: [ dev ]

env:
  REGISTRY_NAME: kelly1311
  IMAGE: app-hello
  TAG: app-maven-v3
  VERSION: 11
  DISTRIBUTION: adopt

jobs:    
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.VERSION}}
          distribution: ${{env.DISTRIBUTION}}
      - name: Test
        run: mvn --batch-mode test

  Publish_package_and_image_build:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.VERSION}}
          distribution: ${{env.DISTRIBUTION}}
      - name: Deploy to Github Package Registry
        env:
          USER_GITHUB: ${{ secrets.USER_GITHUB }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: mvn source:jar install  -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/organizacionkelly/app-maven'


      #login docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      #build and push image
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{env.REGISTRY_NAME}}/${{env.IMAGE}}:${{env.TAG}}
 
  deploy_azure:
      runs-on: ubuntu-latest
      needs: [Publish_package_and_image_build]
      steps:
      - uses: actions/checkout@v2
        #login en azure
      - uses: azure/login@v1
        with:
          username: ${{}}
          password: ${{}}
      - run: |
          az login

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}
      - name: Docker registry download   
        run: docker pull ${{env.REGISTRY_NAME}}/${{IMAGE}}:${{TAG}} 
        run: docker images   

      # Deploy app to AKS
      - name: Deploy
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ${{ github.workspace }}/manifests/${{env.MANIFESTS_YML}}
        
       


        
