on:
  push:
    branches: [main]

jobs:    
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Test
        run: mvn --batch-mode test

  Publish_package_and_image_build:
    runs-on: ubuntu-latest
    needs: [Test]
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Set up Maven Settings for deploy
        uses: s4u/maven-settings-action@v2.1.1
      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: ${{ secrets.USER_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        #run: mvn  --settings settings.xml --file pom.xml deploy -X
       ## run: mvn clean source:jar deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -Dmaven.install.skip=true -DdeplyAtEnd=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/jesusrh12/ffm-ne-back-jv-lib-commons'
        run: mvn  deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/kelly1311/new-repo-maven'
      
     #login docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      #build and push image
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kelly1311/app-hello:maven-v1
  
        
       


        
