on:
  push:
     branches: [develop]

env:
  REGISTRY_NAME: kelly1311
  IMAGE: app-hello
  TAG: app-maven-v2
  VERSION: 11
  DISTRIBUTION: adopt

jobs:  
  deploy_azure:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        #login en azure
      - uses: azure/login@v1
        with:
         
      - run: |
          az login

     